version: '3'
services:
  yii:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - .:/app:delegated
    ports:
      - '8080:80'
    links:
      - 'mysql'

  mysql:
    image: mysql:latest
    container_name: i2crmChatDB
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "TestChatPw"
      MYSQL_DATABASE: 'i2crmChat'

  composer:
    restart: 'no'
    image: library/composer
    # command: composer create-project --prefer-dist yiisoft/yii2-app-basic basic
    command: install --ignore-platform-reqs
    volumes:
      - .:/app

  npm:
    restart: 'no'
    image: node:10
    command: npm install --prefix /app
    volumes:
      - .:/app:delegated

volumes:
  mysql:
